stages:
  - build
  - deploy

variables:
  GIT_CLEAN_FLAGS: none

build-front:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - project/S06P31D108/frontend/node_modules
  only:
    - master
    - develop
  script:
    # - source "/home/ubuntu/.nvm/nvm.sh"
    - cd $CI_PROJECT_DIR/frontend
    - pwd
    - npm install
    - pwd
    - CI=false npm run build
    - sudo rm -rf /home/ubuntu/project/S06P31D108/frontend/build
    - sudo cp -rf build /home/ubuntu/project/S06P31D108/frontend
  tags:
    - prd

deploy-front:
  stage: deploy
  only:
    - master
    - develop
  script:
    - pwd
    - ls -al /home/ubuntu/project/S06P31D108/frontend/build
    - cd $CI_PROJECT_DIR/backend
    - sudo chmod 777 entrypoint.sh
    - sudo chmod 777 manage
    - cd ..
    - ls -al
    - docker-compose up
    - docker ps
  tags:
    - prd
