stages:
  - build
  - deploy

build-front:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - project/S06P31D108/frontend/node_modules
  only:
    - master
    - develop
  script:
    # - source "/home/ubuntu/.nvm/nvm.sh"
    - echo $PROJECT_REPO
    - cd $CI_PROJECT_DIR/frontend
    - pwd
    - npm install
    - CI=false npm run build
    - sudo rm -rf $PROJECT_REPO/frontend/build
    - sudo cp -rf build $PROJECT_REPO/frontend
  tags:
    - prd

deploy-front:
  stage: deploy
  only:
    - master
    - develop
  script:
    - echo $PROJECT_REPO
    - ls -al $PROJECT_REPO/frontend/build
  tags:
    - prd
