stages:
  - build
  - deploy

build-front:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - project/S06P31D108/frontend/node_modules
  only:
    - master
    - develop
  script:
    # - source "/home/ubuntu/.nvm/nvm.sh"
    - echo $PROJECT_REPO
    - cd $CI_PROJECT_DIR/frontend
    - pwd
    - npm install
    - CI=false npm run build
    # - ls -al build
    - rm -rf ~/project/S06P31D108/frontend/build
    - cp -rf build ~/project/S06P31D108/frontend
    # - ls -al
  tags:
    - prd

deploy-front:
  stage: deploy
  only:
    - master
    - develop
  script:
    - echo $PROJECT_REPO
    - ls -al ~/project/S06DP31D108/frontend/build
  tags:
    - prd
