version: "3"
services:
  backend:
    restart: unless-stopped
    container_name: back
    command: chmod +x backend/wsgi-entrypoint.sh
    entrypoint:
      - ./backend/wsgi-entrypoint.sh
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
      - /app/backend/static

  frontend:
    restart: unless-stopped
    container_name: front
    command: npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    stdin_open: true
