version: "3"
services:
  backend:
    restart: always
    container_name: back
    command: chmod +x app/backend/entrypoint.sh
    entrypoint:
      - /app/backend/entrypoint.sh
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  # frontend:
  #   restart: always
  #   container_name: front
  #   command: npm start
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   stdin_open: true
