# Generated by Django 4.0.4 on 2022-04-21 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('payment', models.BigIntegerField(default=0)),
                ('interest', models.BigIntegerField(default=0)),
                ('deadline', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('book_type', models.CharField(choices=[('deposit', '예금'), ('savings', '적금'), ('stock', '주식')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('change', models.IntegerField()),
                ('article', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('bankbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankbooks.bankbook')),
            ],
        ),
    ]
